/**
 * Shared helpers for isolated-V8 subprocess tools.
 *
 * Both NativeBytecodePrinter.ts (--print-bytecode) and TurboFanTraceCollector.ts
 * (--trace-turbo) spawn a dedicated Node.js child with a V8 flag, feed a
 * reconstructed function via stdin, and parse a status marker line from stdout.
 * The function-name normalization, source-shape detection, and status-line
 * parsing are identical across the two tools — kept here so a fix lands once.
 */

/** Identifier that can be bound as a top-level `let` in a bootstrap script. */
export function isValidFunctionName(value: string): boolean {
  return /^[A-Za-z_$][\w$]*$/u.test(value);
}

/**
 * Normalize a user-supplied function name for use as a V8 flag filter value
 * (`--print-bytecode-filter=<name>` / `--trace-turbo-filter=<name>`).
 * Empty, "anonymous", and invalid identifiers fall back to the per-tool
 * bootstrap binding name so the emitted `[generated bytecode for function: X]`
 * / turbo JSON function header always matches the filter.
 */
export function normalizeFunctionName(value: string, fallbackName: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed === 'anonymous') {
    return fallbackName;
  }
  return isValidFunctionName(trimmed) ? trimmed : fallbackName;
}

/**
 * Detect whether a captured source slice is an object-member definition
 * (`name() { ... }` shorthand / `get x()` / `set x()` / `*gen()`) rather than
 * a standalone function/class/arrow expression. Member-style slices can only
 * be bound via an intermediate holder object.
 */
export function shouldWrapAsObjectMember(source: string): boolean {
  const trimmed = source.trim();
  if (
    trimmed.startsWith('function') ||
    trimmed.startsWith('async function') ||
    trimmed.startsWith('class ') ||
    trimmed.startsWith('(') ||
    trimmed.includes('=>')
  ) {
    return false;
  }
  return /^(?:async\s+)?(?:get\s+|set\s+)?\*?\s*[A-Za-z_$][\w$]*\s*\(/u.test(trimmed);
}

/**
 * Extract the tool's status marker line from the child's stdout. The bootstrap
 * script prints `<prefix>done`, `<prefix>resolve-failed`, or
 * `<prefix>invoke-error:<msg>`; V8 flag output (bytecode / turbo JSON) may
 * interleave freely around it.
 */
export function parseStatusLine(output: string, statusPrefix: string): string | null {
  const line = output
    .split(/\r?\n/u)
    .find((entry) => entry.startsWith(statusPrefix) && entry.length > statusPrefix.length);
  return line ? line.slice(statusPrefix.length) : null;
}
