import type { StructureAnalyzer } from '@native/StructureAnalyzer';
import type { FieldType, InferredStruct } from '@native/StructureAnalyzer.types';
import type { UnifiedProcessManager } from '@server/domains/shared/modules/native';
import type { MCPServerContext } from '@server/MCPServer.context';
import { resolveMemoryDomainPid } from '@server/domains/memory/pid-resolver';
import { handleSafe } from '@server/domains/shared/ResponseBuilder';
import { argBool, argNumber, argString, argStringArray } from '@server/domains/shared/parse-args';
import { logger } from '@utils/logger';
import { MemoryAuditTrail } from '@modules/process/memory/AuditTrail';
import { parseJsonArg } from './validation';
import { parseAddressFormula } from './address-formula';
import {
  exportCSharpStruct,
  exportRustStruct,
  detectCompositeTypes,
  setTypeOverride,
  clearTypeOverrides,
  listTypeOverrides,
} from './composite-types';
import { signCheatTable, verifyCheatTable } from './cheat-table-sign';

const TOOL_STRUCTURE_ANALYZE = 'memory_structure_analyze';
const TOOL_VTABLE_PARSE = 'memory_vtable_parse';
const TOOL_STRUCTURE_EXPORT_C = 'memory_structure_export_c';
const TOOL_STRUCTURE_COMPARE = 'memory_structure_compare';
const TOOL_TYPE_DEFINE = 'memory_type_define';

/** Upper bound for structure analysis/compare sizes — reading megabytes into
 * the structure inferencer is almost always a mistake and risks huge reads. */
const STRUCTURE_MAX_SIZE = 64 * 1024;

const FIELD_TYPE_ALIASES: Record<string, FieldType> = {
  int8_t: 'int8',
  uint8_t: 'uint8',
  int16_t: 'int16',
  uint16_t: 'uint16',
  int32_t: 'int32',
  uint32_t: 'uint32',
  int64_t: 'int64',
  uint64_t: 'uint64',
  void_ptr: 'pointer',
  char_ptr: 'string_ptr',
};

function normalizeFieldType(value: unknown): FieldType {
  if (typeof value !== 'string' || value.length === 0) return 'unknown';
  const normalized = value.toLowerCase().replace(/\s+/g, '_').replace(/\*/g, '_ptr');
  return FIELD_TYPE_ALIASES[normalized] ?? (normalized as FieldType);
}

/** Map jshookmcp field types to ReClass.NET node types. */
const RECLASS_TYPE_MAP: Record<string, string> = {
  int8: 'int8',
  uint8: 'uint8',
  int16: 'int16',
  uint16: 'uint16',
  int32: 'int32',
  uint32: 'uint32',
  int64: 'int64',
  uint64: 'uint64',
  float: 'float',
  double: 'double',
  pointer: 'ptr64',
  string_ptr: 'ptr64',
  vtable_ptr: 'vt_ptr',
  hex: 'hex32',
  padding: 'Bytes',
  unknown: 'hex32',
};

/**
 * Generate a ReClass.NET 1.0 XML project from an inferred structure.
 * Each field maps to a `<Node>` with the appropriate ReClass type, offset,
 * and size. The XML is importable by ReClass.NET via File → Open.
 */
function exportReClassXml(structure: InferredStruct, name: string): string {
  const safeName = name.replace(/[<>&"']/g, '');
  const nodes = structure.fields
    .map((f) => {
      const reclassType = RECLASS_TYPE_MAP[f.type] ?? 'hex32';
      const offsetHex = `0x${f.offset.toString(16).padStart(2, '0').toUpperCase()}`;
      const comment = f.notes ? ` Comment="${escapeXml(f.notes)}"` : '';
      return `    <Node Name="${escapeXml(f.name)}" Type="${reclassType}" Offset="${offsetHex}" Size="${f.size}"${comment}/>`;
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<ReClassProject Version="1.0">',
    `  <Class Name="${safeName}" Comment="Auto-generated by jshookmcp" Offset="0">`,
    nodes,
    '  </Class>',
    '</ReClassProject>',
    '',
  ].join('\n');
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function normalizeStructureForExport(raw: unknown): InferredStruct {
  if (!raw || typeof raw !== 'object') {
    throw new Error('structure must be a JSON object');
  }

  const source = raw as Record<string, unknown>;
  const rawFields = Array.isArray(source.fields) ? source.fields : [];
  const fields = rawFields.map((entry, index) => {
    const field = entry as Record<string, unknown>;
    const offset = typeof field.offset === 'number' ? field.offset : 0;
    const size = typeof field.size === 'number' ? field.size : 1;

    return {
      offset,
      size,
      type: normalizeFieldType(field.type),
      name: typeof field.name === 'string' && field.name.length > 0 ? field.name : `field_${index}`,
      value: typeof field.value === 'string' ? field.value : '',
      confidence: typeof field.confidence === 'number' ? field.confidence : 1,
      notes: typeof field.notes === 'string' ? field.notes : undefined,
    };
  });
  const inferredSize = fields.reduce((max, field) => Math.max(max, field.offset + field.size), 0);
  const totalSize =
    typeof source.totalSize === 'number'
      ? source.totalSize
      : typeof source.size === 'number'
        ? source.size
        : inferredSize;

  return {
    baseAddress: typeof source.baseAddress === 'string' ? source.baseAddress : '0x0',
    totalSize,
    fields,
    vtableAddress: typeof source.vtableAddress === 'string' ? source.vtableAddress : undefined,
    className: typeof source.className === 'string' ? source.className : undefined,
    baseClasses: Array.isArray(source.baseClasses)
      ? source.baseClasses.filter((entry): entry is string => typeof entry === 'string')
      : undefined,
    timestamp: typeof source.timestamp === 'number' ? source.timestamp : Date.now(),
  };
}

export class StructureHandlers {
  private readonly structAnalyzer: StructureAnalyzer;
  private readonly processManager?: UnifiedProcessManager;
  private readonly ctx?: MCPServerContext;
  private readonly auditTrail: MemoryAuditTrail | null;

  constructor(
    structAnalyzer: StructureAnalyzer,
    processManager?: UnifiedProcessManager,
    ctx?: MCPServerContext,
    auditTrail?: MemoryAuditTrail | null,
  ) {
    this.structAnalyzer = structAnalyzer;
    this.processManager = processManager;
    this.ctx = ctx;
    this.auditTrail = auditTrail ?? null;
  }

  private async resolvePid(value: unknown): Promise<number> {
    return await resolveMemoryDomainPid(value, this.processManager, this.ctx);
  }

  private recordAudit(entry: {
    operation: string;
    pid: number | null;
    address: string | null;
    size: number | null;
    result: 'success' | 'failure';
    error?: string;
    durationMs: number;
  }): void {
    if (!this.auditTrail) return;
    try {
      this.auditTrail.record(entry);
    } catch (auditError) {
      logger.warn('Memory audit trail recording failed:', auditError);
    }
  }

  async handleStructureAnalyze(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const pid = await this.resolvePid(args.pid);
      const addressRaw = argString(args, 'address');
      if (!addressRaw) {
        throw new Error(
          `${TOOL_STRUCTURE_ANALYZE}: missing or invalid required argument "address" (expected hex or address formula, e.g. "0x7FF612340000 + 0x10")`,
        );
      }
      const formula = parseAddressFormula(addressRaw);
      if (!formula.address) {
        throw new Error(`${TOOL_STRUCTURE_ANALYZE}: ${formula.error}`);
      }
      const address = formula.address;
      const size = argNumber(args, 'size');
      if (size !== undefined && (!Number.isFinite(size) || size <= 0)) {
        throw new Error(
          `${TOOL_STRUCTURE_ANALYZE}: argument "size" must be a positive number, got: ${JSON.stringify(args.size)}`,
        );
      }
      if (size !== undefined && size > STRUCTURE_MAX_SIZE) {
        throw new Error(
          `${TOOL_STRUCTURE_ANALYZE}: size ${size} exceeds maximum ${STRUCTURE_MAX_SIZE} bytes (64KB). Analyze a smaller region or narrow the address first.`,
        );
      }
      const otherInstances = argStringArray(args, 'otherInstances');
      const parseRtti = argBool(args, 'parseRtti', true);
      const start = Date.now();
      const result = await this.structAnalyzer.analyzeStructure(pid, address, {
        size,
        otherInstances,
        parseRtti,
      });
      this.recordAudit({
        operation: 'structure_analyze',
        pid,
        address,
        size: result.fields?.length ?? 0,
        result: 'success',
        durationMs: Date.now() - start,
      });
      return {
        ...result,
        hint: result.className
          ? `Detected class: ${result.className}` +
            `${result.baseClasses?.length ? ` (inherits: ${result.baseClasses.join(' → ')})` : ''}`
          : `Inferred ${result.fields.length} fields. Use memory_structure_export_c to export as C struct.`,
      };
    });
  }

  async handleVtableParse(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const pid = await this.resolvePid(args.pid);
      const vtableRaw = argString(args, 'vtableAddress');
      if (!vtableRaw) {
        throw new Error(
          `${TOOL_VTABLE_PARSE}: missing or invalid required argument "vtableAddress"`,
        );
      }
      const formula = parseAddressFormula(vtableRaw);
      if (!formula.address) {
        throw new Error(`${TOOL_VTABLE_PARSE}: ${formula.error}`);
      }
      const vtableAddress = formula.address;
      // x64 vtables must be pointer-aligned (8 bytes). A misaligned address
      // produces garbage entries or a fault — reject before the native read.
      const vtableBig = BigInt(`0x${vtableAddress.toLowerCase().replace(/^0x/, '')}`);
      if (vtableBig % 8n !== 0n) {
        throw new Error(
          `${TOOL_VTABLE_PARSE}: vtableAddress ${vtableAddress} is not 8-byte aligned. x64 vtables must be pointer-aligned (address divisible by 8).`,
        );
      }
      return { ...(await this.structAnalyzer.parseVtable(pid, vtableAddress)) };
    });
  }

  async handleStructureExportC(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const structure = argString(args, 'structure');
      if (!structure) {
        throw new Error(
          `${TOOL_STRUCTURE_EXPORT_C}: missing or invalid required argument "structure" (expected JSON string), got: ${JSON.stringify(args.structure)}`,
        );
      }
      const parsed = parseJsonArg(structure, 'structure', TOOL_STRUCTURE_EXPORT_C);
      const normalized = normalizeStructureForExport(parsed);
      const format = typeof args.format === 'string' ? args.format : 'c';
      const name =
        typeof args.name === 'string' && args.name.length > 0
          ? args.name
          : (normalized.className ?? 'UnknownStruct');

      if (format === 'reclass') {
        const xml = exportReClassXml(normalized, name);
        return {
          format: 'reclass',
          xml,
          fieldCount: normalized.fields.length,
          hint: `Exported ${normalized.fields.length} fields to ReClass.NET XML. Open in ReClass.NET via File → Open.`,
        };
      }

      if (format === 'rust') {
        const definition = exportRustStruct(normalized, name);
        return {
          format: 'rust',
          definition,
          name,
          fieldCount: normalized.fields.length,
          size: normalized.totalSize,
          hint: `Exported ${normalized.fields.length} fields as Rust #[repr(C)] struct.`,
        };
      }

      if (format === 'csharp') {
        const definition = exportCSharpStruct(normalized, name);
        return {
          format: 'csharp',
          definition,
          name,
          fieldCount: normalized.fields.length,
          size: normalized.totalSize,
          hint: `Exported ${normalized.fields.length} fields as C# [StructLayout] struct.`,
        };
      }

      // Default: C format
      const compositeDetections = detectCompositeTypes(normalized.fields);
      const cResult = this.structAnalyzer.exportToCStruct(normalized, name);
      return {
        format: 'c',
        ...cResult,
        compositeTypes: compositeDetections.length > 0 ? compositeDetections : undefined,
        hint:
          compositeDetections.length > 0
            ? `Exported ${normalized.fields.length} fields as C struct. Detected ${compositeDetections.length} composite type(s): ${compositeDetections.map((d) => d.suggestedType).join(', ')}.`
            : undefined,
      };
    });
  }

  async handleStructureCompare(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const pid = await this.resolvePid(args.pid);

      const addr1Raw = argString(args, 'address1');
      if (!addr1Raw) {
        throw new Error(
          `${TOOL_STRUCTURE_COMPARE}: missing or invalid required argument "address1"`,
        );
      }
      const f1 = parseAddressFormula(addr1Raw);
      if (!f1.address) throw new Error(`${TOOL_STRUCTURE_COMPARE}: ${f1.error}`);
      const address1 = f1.address;

      const addr2Raw = argString(args, 'address2');
      if (!addr2Raw) {
        throw new Error(
          `${TOOL_STRUCTURE_COMPARE}: missing or invalid required argument "address2"`,
        );
      }
      const f2 = parseAddressFormula(addr2Raw);
      if (!f2.address) throw new Error(`${TOOL_STRUCTURE_COMPARE}: ${f2.error}`);
      const address2 = f2.address;
      const size = argNumber(args, 'size');
      if (size !== undefined && (!Number.isFinite(size) || size <= 0)) {
        throw new Error(
          `${TOOL_STRUCTURE_COMPARE}: argument "size" must be a positive number, got: ${JSON.stringify(args.size)}`,
        );
      }
      if (size !== undefined && size > STRUCTURE_MAX_SIZE) {
        throw new Error(
          `${TOOL_STRUCTURE_COMPARE}: size ${size} exceeds maximum ${STRUCTURE_MAX_SIZE} bytes (64KB). Compare a smaller region.`,
        );
      }
      // ── Group comparison mode (CE dissect data parity) ──
      const group1Raw = args.group1Addresses;
      const group2Raw = args.group2Addresses;
      if (
        (Array.isArray(group1Raw) && group1Raw.length > 0) ||
        (Array.isArray(group2Raw) && group2Raw.length > 0)
      ) {
        return this.handleGroupStructureCompare(args, pid, size);
      }

      const result = await this.structAnalyzer.compareInstances(pid, address1, address2, size);
      return {
        matchingFieldCount: result.matching.length,
        differingFieldCount: result.differing.length,
        ...result,
      };
    });
  }

  /**
   * Group structure comparison: read all instances from group1Addresses and
   * group2Addresses, compute per-offset statistics, and report:
   * - Fields that differ BETWEEN groups (gameplay state)
   * - Fields constant WITHIN a group but different between groups (identity)
   * - Fields constant across ALL instances (vtable, type flags)
   */
  private async handleGroupStructureCompare(
    args: Record<string, unknown>,
    pid: number,
    size?: number,
  ) {
    const group1Raw = (Array.isArray(args.group1Addresses) ? args.group1Addresses : []) as string[];
    const group2Raw = (Array.isArray(args.group2Addresses) ? args.group2Addresses : []) as string[];
    const allAddrs = [...group1Raw, ...group2Raw];
    const effectiveSize = size ?? 256;

    if (allAddrs.length === 0) {
      throw new Error(
        `${TOOL_STRUCTURE_COMPARE}: group comparison requires at least one address in group1Addresses or group2Addresses`,
      );
    }

    if (effectiveSize > STRUCTURE_MAX_SIZE) {
      throw new Error(
        `${TOOL_STRUCTURE_COMPARE}: size ${effectiveSize} exceeds maximum ${STRUCTURE_MAX_SIZE} bytes`,
      );
    }

    // Read all instances via the platform provider (b3-09/a4-01 async migration,
    // commit c047a09b): the previous structAnalyzer.readMemory path called koffi
    // synchronously on the event loop. createPlatformProvider().readMemory routes
    // through the `.async` worker path so per-instance group reads do not block.
    // (Hygiene debt: MemoryController's win32 readBuffer stays synchronous for
    // low-frequency single reads — this hot multi-read path bypasses it directly.)
    const { createPlatformProvider } = await import('@native/platform/factory.js');
    const provider = createPlatformProvider();
    const handle = provider.openProcess(pid, false);
    const instances: Array<{ group: 1 | 2; bytes: Buffer }> = [];
    try {
      for (let i = 0; i < group1Raw.length; i++) {
        const addr = group1Raw[i]!;
        const formula = parseAddressFormula(addr);
        if (!formula.address) {
          throw new Error(
            `${TOOL_STRUCTURE_COMPARE}: invalid group1 address at index ${i}: ${formula.error}`,
          );
        }
        const raw = (await provider.readMemory(handle, BigInt(formula.address), effectiveSize))
          .data;
        instances.push({ group: 1, bytes: Buffer.from(raw) });
      }
      for (let i = 0; i < group2Raw.length; i++) {
        const addr = group2Raw[i]!;
        const formula = parseAddressFormula(addr);
        if (!formula.address) {
          throw new Error(
            `${TOOL_STRUCTURE_COMPARE}: invalid group2 address at index ${i}: ${formula.error}`,
          );
        }
        const raw = (await provider.readMemory(handle, BigInt(formula.address), effectiveSize))
          .data;
        instances.push({ group: 2, bytes: Buffer.from(raw) });
      }
    } finally {
      provider.closeProcess(handle);
    }

    const group1Instances = instances.filter((i) => i.group === 1);
    const group2Instances = instances.filter((i) => i.group === 2);

    // Per-offset analysis
    const matches: Array<{ offset: number; size: number; description: string }> = [];
    const diffs: Array<{
      offset: number;
      size: number;
      description: string;
      group1Values: string[];
      group2Values: string[];
      confidence: number;
      category: 'between_groups' | 'within_group' | 'constant_all';
    }> = [];

    for (let off = 0; off < effectiveSize; off += 4) {
      const readSize = Math.min(4, effectiveSize - off);

      // Collect values per group
      const g1Vals = group1Instances.map((inst) => readUInt(inst.bytes, off, readSize));
      const g2Vals = group2Instances.map((inst) => readUInt(inst.bytes, off, readSize));
      const allVals = [...g1Vals, ...g2Vals];

      // Check: all identical across every instance?
      const allSame = allVals.every((v) => v === allVals[0]);
      if (allSame) {
        matches.push({
          offset: off,
          size: readSize,
          description:
            allVals[0] === 0
              ? `Constant zero across all ${instances.length} instances (likely padding or null pointer)`
              : `Constant value 0x${allVals[0]!.toString(16)} across all ${instances.length} instances (likely vtable, type flag, or static data)`,
        });
        continue;
      }

      // Check: same within each group, different between groups
      const g1Same = g1Vals.every((v) => v === g1Vals[0]);
      const g2Same = g2Vals.every((v) => v === g2Vals[0]);
      if (g1Same && g2Same && g1Vals[0] !== g2Vals[0]) {
        diffs.push({
          offset: off,
          size: readSize,
          description: `Differs between groups: Group1=0x${g1Vals[0]!.toString(16)}, Group2=0x${g2Vals[0]!.toString(16)}`,
          group1Values: g1Vals.map((v) => `0x${v!.toString(16)}`),
          group2Values: g2Vals.map((v) => `0x${v!.toString(16)}`),
          confidence: 0.85,
          category: 'between_groups',
        });
        continue;
      }

      // Check: varies within groups (dynamic state)
      const g1Varies = new Set(g1Vals).size > 1;
      const g2Varies = new Set(g2Vals).size > 1;
      if (g1Varies || g2Varies) {
        diffs.push({
          offset: off,
          size: readSize,
          description: `Varies within groups — likely dynamic runtime state (health, position, timer)`,
          group1Values: g1Vals.map((v) => `0x${v!.toString(16)}`),
          group2Values: g2Vals.map((v) => `0x${v!.toString(16)}`),
          confidence: 0.6,
          category: 'within_group',
        });
        continue;
      }

      // Fallthrough
      matches.push({
        offset: off,
        size: readSize,
        description: `No clear pattern at offset 0x${off.toString(16)}`,
      });
    }

    return {
      totalInstances: instances.length,
      group1Count: group1Instances.length,
      group2Count: group2Instances.length,
      compareSize: effectiveSize,
      matchingFieldCount: matches.length,
      differingFieldCount: diffs.length,
      matches,
      differing: diffs,
      categorySummary: {
        between_groups: diffs.filter((d) => d.category === 'between_groups').length,
        within_group: diffs.filter((d) => d.category === 'within_group').length,
        constant_all: matches.length,
      },
    };
  }

  // ── Type Define ──

  async handleTypeDefine(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const offset = argNumber(args, 'offset');
      if (offset === undefined || !Number.isFinite(offset) || offset < 0) {
        throw new Error(`${TOOL_TYPE_DEFINE}: missing or invalid required argument "offset"`);
      }
      const size = argNumber(args, 'size');
      if (size === undefined || !Number.isFinite(size) || size <= 0) {
        throw new Error(`${TOOL_TYPE_DEFINE}: missing or invalid required argument "size"`);
      }
      const type = argString(args, 'type');
      if (!type) {
        throw new Error(`${TOOL_TYPE_DEFINE}: missing or invalid required argument "type"`);
      }

      const action = typeof args.action === 'string' ? args.action : 'set';
      if (action === 'clear') {
        clearTypeOverrides();
        return {
          success: true,
          action: 'clear',
          hint: 'All type overrides cleared.',
        };
      }

      if (action === 'list') {
        return {
          success: true,
          action: 'list',
          overrides: listTypeOverrides(),
        };
      }

      // action === 'set'
      const normalized = normalizeFieldType(type);
      setTypeOverride(offset, size, normalized);
      return {
        success: true,
        action: 'set',
        offset,
        size,
        type: normalized,
        hint: `Type override set: offset 0x${offset.toString(16)}, size ${size} → ${normalized}. Use memory_structure_analyze to re-analyze with overrides applied.`,
      };
    });
  }

  // ── Cheat Table Import/Export/Sign/Verify ──

  async handleCheatTableExport(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const rawEntries = args.entries;
      if (!Array.isArray(rawEntries)) {
        throw new Error(
          'memory_cheat_table export: missing or invalid argument "entries" (expected array of {description, address, valueType})',
        );
      }
      const { exportCheatTable, mapValueTypeToCE, formatModuleAddress } =
        await import('@native/CheatTableIO');

      const entries = rawEntries.map((entry: unknown, i: number) => {
        const e = entry as Record<string, unknown>;
        const description = typeof e.description === 'string' ? e.description : `Entry ${i}`;
        const address = typeof e.address === 'string' ? e.address : '0x0';
        const valueType = typeof e.valueType === 'string' ? e.valueType : 'int32';
        const moduleName = typeof e.moduleName === 'string' ? e.moduleName : undefined;
        const offset = typeof e.offset === 'string' ? e.offset : undefined;

        // If module-relative, build CE-style address
        const ceType = mapValueTypeToCE(valueType);
        const ceAddress = moduleName && offset ? formatModuleAddress(moduleName, offset) : address;

        return { description, address: ceAddress, variableType: ceType };
      });

      const version = typeof args.version === 'number' && args.version > 0 ? args.version : 45;
      const xml = exportCheatTable(entries, version);

      // If sign action is requested, sign after export
      const action = typeof args.action === 'string' ? args.action : 'export';
      if (action === 'sign') {
        const signResult = await signCheatTable(xml, args);
        if (!signResult.success) {
          return {
            success: false,
            exportSuccess: true,
            xml,
            entryCount: entries.length,
            version,
            signError: signResult.error,
          };
        }
        return {
          success: true,
          xml: signResult.signedXml,
          entryCount: entries.length,
          version,
          signed: true,
          signature: signResult.signature,
          signer: signResult.signer,
          timestamp: signResult.timestamp,
          hint: 'Cheat table exported and signed. Use memory_cheat_table action=verify to validate.',
        };
      }

      return {
        success: true,
        xml,
        entryCount: entries.length,
        version,
      };
    });
  }

  async handleCheatTableImport(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const xml = argString(args, 'xml');
      if (!xml) {
        throw new Error(
          'memory_cheat_table import: missing or invalid argument "xml" (expected CT XML string)',
        );
      }
      const { importCheatTable, mapCEToValueType } = await import('@native/CheatTableIO');

      const result = importCheatTable(xml);

      // Map CE VariableType back to jshookmcp types
      const mappedEntries = result.entries.map((entry) => ({
        ...entry,
        valueType: mapCEToValueType(entry.variableType),
      }));

      return {
        success: true,
        entries: mappedEntries,
        entryCount: mappedEntries.length,
        warnings: result.warnings,
      };
    });
  }

  async handleCheatTableSign(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const xml = argString(args, 'xml');
      if (!xml) {
        throw new Error(
          'memory_cheat_table sign: missing or invalid argument "xml" (expected CT XML string)',
        );
      }
      const result = await signCheatTable(xml, args);
      if (!result.success) {
        return { success: false, error: result.error };
      }
      return {
        success: true,
        signedXml: result.signedXml,
        signature: result.signature,
        signer: result.signer,
        timestamp: result.timestamp,
        entryCount: result.entryCount,
        hint: 'Cheat table signed. Use memory_cheat_table action=verify to validate the signature.',
      };
    });
  }

  async handleCheatTableVerify(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const xml = argString(args, 'xml');
      if (!xml) {
        throw new Error(
          'memory_cheat_table verify: missing or invalid argument "xml" (expected CT XML string)',
        );
      }
      const result = await verifyCheatTable(xml, args);
      return {
        success: true,
        valid: result.valid,
        signer: result.signer,
        timestamp: result.timestamp,
        error: result.error,
        hint: result.valid
          ? `Signature valid — signed by "${result.signer}" at ${new Date(result.timestamp!).toISOString()}.`
          : (result.error ?? 'Signature verification failed.'),
      };
    });
  }

  // ── RTTI Standalone ──

  async handleRttiInfo(args: Record<string, unknown>) {
    return handleSafe(async () => {
      const pid = await this.resolvePid(args.pid);
      const addressRaw = argString(args, 'address');
      if (!addressRaw) {
        throw new Error(
          'memory_rtti_info: missing or invalid required argument "address" (expected hex address, e.g. "0x7FF612340000")',
        );
      }
      const formula = parseAddressFormula(addressRaw);
      if (!formula.address) {
        throw new Error(`memory_rtti_info: ${formula.error}`);
      }
      const address = formula.address;

      const start = Date.now();
      const result = await this.structAnalyzer.parseRtti(pid, address);
      const elapsed = `${(performance.now() - start).toFixed(1)}ms`;

      if (!result) {
        return {
          success: true,
          found: false,
          hint: 'No valid RTTI found at this address. The object may not have RTTI enabled, or the address may not point to a vtable-backed MSVC object.',
          elapsed,
        };
      }

      return {
        success: true,
        found: true,
        className: result.className,
        baseClasses: result.baseClasses,
        elapsed,
        hint: `Class: ${result.className}${result.baseClasses.length > 0 ? ` (inherits: ${result.baseClasses.join(' → ')})` : ''}`,
      };
    });
  }
}

/** Read a little-endian unsigned integer from a buffer at offset. */
function readUInt(buf: Buffer, offset: number, size: number): number {
  switch (size) {
    case 1:
      return buf.readUInt8(offset);
    case 2:
      return buf.readUInt16LE(offset);
    case 4:
      return buf.readUInt32LE(offset);
    default:
      return buf.readUInt32LE(offset);
  }
}
