export interface CrossDomainWorkflowStep {
  tool: string;
  args: Record<string, unknown>;
}

export interface CrossDomainWorkflowDefinition {
  id: string;
  displayName: string;
  keywords: string[];
  steps: CrossDomainWorkflowStep[];
}

export const WORKFLOWS: Record<string, CrossDomainWorkflowDefinition> = {
  WORKFLOW_REVERSE_OBFUSCATED: {
    id: 'reverse-obfuscated-api',
    displayName: 'Reverse Obfuscated API',
    keywords: [
      'obfuscated',
      'deobfuscate',
      'api',
      'fetch',
      'signature',
      'sign',
      'tls',
      'pin',
      'crypto',
      'token',
      '加密',
      '签名',
    ],
    steps: [
      { tool: 'deobfuscate', args: { targetUrl: '${input.targetUrl}' } },
      { tool: 'js_heap_search', args: { pattern: '${previous.cryptoKeys}' } },
      { tool: 'network_enable', args: {} },
      { tool: 'tls_cert_pin_bypass', args: { target: '${input.target}' } },
      { tool: 'console_inject_fetch_interceptor', args: { urls: ['${input.apiEndpoint}'] } },
    ],
  },
  WORKFLOW_GAME_CANVAS_SKIA: {
    id: 'game-canvas-skia-v8',
    displayName: 'Game Canvas + SKIA + V8 Analysis',
    keywords: [
      'game',
      'canvas',
      'skia',
      'scene',
      'sprite',
      'render',
      'draw',
      'heap',
      'v8',
      '游戏',
      '渲染',
    ],
    steps: [
      { tool: 'canvas_engine_fingerprint', args: { canvasId: '${input.canvasId}' } },
      { tool: 'canvas_scene_dump', args: { canvasId: '${input.canvasId}' } },
      { tool: 'skia_correlate_objects', args: { skiaNodeIds: '${previous.nodeIds}' } },
      { tool: 'performance_take_heap_snapshot', args: {} },
      { tool: 'js_heap_search', args: { pattern: '${input.searchTerm}' } },
    ],
  },
  WORKFLOW_BINARY_NATIVE_HOOK: {
    id: 'binary-native-hook',
    displayName: 'Binary Analysis + Native Hook',
    keywords: [
      'binary',
      'native',
      'hook',
      'frida',
      'ghidra',
      'symbol',
      'interceptor',
      'jni',
      'so',
      '二进制',
      '原生',
    ],
    steps: [
      { tool: 'ghidra_analyze', args: { binaryPath: '${input.binaryPath}' } },
      { tool: 'generate_hooks', args: { symbols: '${previous.exportedSymbols}' } },
      { tool: 'frida_attach', args: { target: '${input.target}' } },
      { tool: 'frida_run_script', args: { script: '${previous.hookScript}' } },
    ],
  },
  WORKFLOW_NETWORK_V8_INITIATOR: {
    id: 'network-v8-initiator',
    displayName: 'Network Request + V8 Initiator Trace',
    keywords: [
      'network',
      'request',
      'api',
      'fetch',
      'xhr',
      'initiator',
      'caller',
      'signature',
      'sign',
      'auth',
      'token',
      'heap',
      'v8',
      '请求',
      '调用方',
      '签名',
    ],
    steps: [
      { tool: 'network_enable', args: {} },
      { tool: 'network_get_requests', args: { limit: 200 } },
      { tool: 'network_extract_auth', args: { includeHeaders: true } },
      { tool: 'performance_take_heap_snapshot', args: {} },
      { tool: 'js_heap_search', args: { pattern: '${input.searchTerm}' } },
      {
        tool: 'cross_domain_correlate_all',
        args: { pullFromDomains: true, minConfidence: 0.4 },
      },
    ],
  },
  WORKFLOW_DEBUGGER_V8_CONTEXT: {
    id: 'debugger-v8-pause-context',
    displayName: 'Debugger Pause + V8 Context Capture',
    keywords: [
      'debugger',
      'breakpoint',
      'pause',
      'stack',
      'scope',
      'frame',
      'run to',
      'cursor',
      'source',
      'v8',
      'heap',
      '断点',
      '暂停',
      '调用栈',
    ],
    steps: [
      { tool: 'debugger_lifecycle', args: { action: 'enable' } },
      { tool: 'breakpoint', args: { action: 'set', type: 'code' } },
      { tool: 'debugger_wait_for_paused', args: { timeout: 30000 } },
      { tool: 'get_call_stack', args: {} },
      { tool: 'get_scope_variables_enhanced', args: { includeObjectProperties: true } },
      { tool: 'js_heap_search', args: { pattern: '${input.searchTerm}' } },
    ],
  },
  WORKFLOW_WASM_MEMORY_TRACE: {
    id: 'wasm-memory-trace',
    displayName: 'WASM Linear Memory + Native Memory Trace',
    keywords: [
      'wasm',
      'webassembly',
      'linear memory',
      'memory',
      'heap',
      'pointer',
      'import',
      'export',
      'trace',
      '写内存',
      '线性内存',
    ],
    steps: [
      { tool: 'wasm_dump', args: { outDir: '${input.outDir}' } },
      { tool: 'wasm_disassemble', args: { wasmPath: '${previous.wasmPath}' } },
      { tool: 'wasm_memory_inspect', args: { moduleIndex: 0 } },
      { tool: 'memory_find_accesses', args: { address: '${input.address}', accessType: 'write' } },
      { tool: 'memory_pointer_chain', args: { address: '${input.address}' } },
    ],
  },
  WORKFLOW_GRAPHQL_API_REPLAY: {
    id: 'graphql-api-replay',
    displayName: 'GraphQL Schema + Network Replay',
    keywords: [
      'graphql',
      'schema',
      'query',
      'mutation',
      'introspection',
      'replay',
      'api',
      'network',
      'headers',
      'token',
    ],
    steps: [
      { tool: 'network_enable', args: {} },
      { tool: 'graphql_extract_queries', args: { source: '${input.source}' } },
      { tool: 'graphql_introspect', args: { endpoint: '${input.endpoint}' } },
      { tool: 'network_extract_auth', args: { includeHeaders: true } },
      { tool: 'graphql_replay', args: { endpoint: '${input.endpoint}' } },
    ],
  },
};
