#!/usr/bin/env node
/**
 * sandbox-export — trace sandbox execution, extract used modules,
 * generate a self-contained Node.js signer script.
 *
 * Usage:
 *   node scripts/sandbox-export.mjs <appid> \
 *     --entry "npm/some-sdk/index.js" \
 *     --fn sign \
 *     --verify "requireMod('npm/some-sdk/index.js').sign({ts:1})" \
 *     --output signer.mjs
 */
import { loadBundle } from "./lib/wx-sandbox.mjs";
import { existsSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, "..");

function findBundle(appid) {
  const names = ["app-service.js", "appservice.app.js"];
  // mp_analyze 解包产物：static/out/<appid>/app/（与解包端路径约定一致，免手动建软链）
  const outApp = join(PROJECT_ROOT, "static", "out", appid, "app");
  for (const n of names) { const c = join(outApp, n); if (existsSync(c)) return c; }
  // 回退：static/unpacked/<appid>/[<ver>/]
  const unpackDir = join(PROJECT_ROOT, "static", "unpacked", appid);
  if (existsSync(unpackDir)) {
    const versions = readdirSync(unpackDir).filter(d => /^\d+$/.test(d)).sort((a, b) => +b - +a);
    for (const ver of versions) for (const n of names) { const c = join(unpackDir, ver, n); if (existsSync(c)) return c; }
    for (const n of names) { const c = join(unpackDir, n); if (existsSync(c)) return c; }
  }
  return null;
}

function parseArgs() {
  const args = process.argv.slice(2);
  const o = { appid: null, entry: null, fn: null, verify: null, output: null, bundlePath: null, storage: {} };
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--entry" && args[i + 1]) o.entry = args[++i];
    else if (args[i] === "--fn" && args[i + 1]) o.fn = args[++i];
    else if (args[i] === "--verify" && args[i + 1]) o.verify = args[++i];
    else if (args[i] === "--output" && args[i + 1]) o.output = args[++i];
    else if (args[i] === "--bundle" && args[i + 1]) o.bundlePath = args[++i];
    else if (args[i] === "--storage" && args[i + 1]) o.storage = JSON.parse(args[++i]);
    else if (!args[i].startsWith("-")) o.appid = args[i];
  }
  return o;
}

function generateStandalone(ctx, usedKeys, opts) {
  const L = [];

  L.push(`#!/usr/bin/env node`);
  L.push(`/**`);
  L.push(` * Standalone signer — ${opts.appid}`);
  L.push(` * Entry module : ${opts.entry}`);
  L.push(` * Export       : ${opts.fn || "default"}`);
  L.push(` * Modules      : ${usedKeys.length} extracted`);
  L.push(` * Generated by : wx-mp-mcp sandbox-export`);
  L.push(` *`);
  L.push(` * Usage:`);
  if (opts.fn) {
    L.push(` *   node ${opts.output || "signer.mjs"} '{"ts":"1719000000","param":"value"}'`);
  }
  L.push(` */`);
  L.push(``);

  // ── Minimal require runtime ──
  L.push(`// ── Runtime (mini WeChat module system) ──`);
  L.push(`const _m = {};`);
  L.push(`const _c = {};`);
  L.push(``);
  L.push(`function _norm(p) {`);
  L.push(`  const parts = p.split("/"), out = [];`);
  L.push(`  for (const s of parts) {`);
  L.push(`    if (s === "" || s === ".") continue;`);
  L.push(`    if (s === "..") out.pop(); else out.push(s);`);
  L.push(`  }`);
  L.push(`  return out.join("/");`);
  L.push(`}`);
  L.push(`function _dir(p) { const i = p.lastIndexOf("/"); return i < 0 ? "" : p.slice(0, i); }`);
  L.push(``);
  L.push(`function _resolve(from, spec) {`);
  L.push(`  const base = spec.startsWith(".") ? _norm(_dir(from) + "/" + spec) : _norm(spec);`);
  L.push(`  for (const c of [base, base + ".js", base + "/index.js", base + ".cjs.js"]) {`);
  L.push(`    if (c in _m) return c;`);
  L.push(`  }`);
  L.push(`  return null;`);
  L.push(`}`);
  L.push(``);
  L.push(`function _req(from, spec) {`);
  L.push(`  const key = _resolve(from, spec);`);
  L.push(`  if (!key) return {};`);
  L.push(`  if (_c[key]) return _c[key];`);
  L.push(`  const mod = { exports: {} };`);
  L.push(`  _c[key] = mod.exports;`);
  L.push(`  const localReq = (s) => _req(key, s);`);
  L.push(`  _m[key](localReq, mod, mod.exports, void 0, void 0, void 0, globalThis);`);
  L.push(`  _c[key] = mod.exports;`);
  L.push(`  return mod.exports;`);
  L.push(`}`);
  L.push(``);

  // ── WeChat stubs ──
  L.push(`// ── WeChat API stubs ──`);
  L.push(`const _storage = ${JSON.stringify(opts.storage || {})};`);
  L.push(`let _appInst = null;`);
  L.push(``);
  L.push(`globalThis.wx = {`);
  L.push(`  getStorageSync: (k) => _storage[k] ?? "",`);
  L.push(`  setStorageSync: (k, v) => { _storage[k] = v; },`);
  L.push(`  getStorage: (o) => { o.success?.({ data: _storage[o.key] }); },`);
  L.push(`  setStorage: (o) => { _storage[o.key] = o.data; o.success?.({}); o.complete?.({}); },`);
  L.push(`  removeStorageSync: (k) => { delete _storage[k]; },`);
  L.push(`  getAccountInfoSync: () => ({ miniProgram: { appId: ${JSON.stringify(opts.appid)}, envVersion: "release" } }),`);
  L.push(`  getSystemInfoSync: () => ({ platform: "mac", system: "Mac OS X 14.2.0", version: "8.0.0", SDKVersion: "3.8.7", model: "Mac15,3", brand: "apple" }),`);
  L.push(`  getDeviceInfo: () => ({ platform: "mac", system: "Mac OS X 14.2.0", model: "Mac15,3", brand: "apple" }),`);
  L.push(`  getAppBaseInfo: () => ({ SDKVersion: "3.8.7", version: "8.0.0", language: "zh_CN" }),`);
  L.push(`  getLaunchOptionsSync: () => ({ scene: 1001, path: "", query: {} }),`);
  L.push(`  getEnterOptionsSync: () => ({ scene: 1001, path: "", query: {} }),`);
  L.push(`  getNetworkType: (o) => o.success?.({ networkType: "wifi" }),`);
  L.push(`  getPerformance: () => ({ now: () => Date.now(), createObserver: () => ({ observe(){}, disconnect(){} }), getEntries: () => [] }),`);
  L.push(`  getBatteryInfoSync: () => ({ level: 80, isCharging: false }),`);
  L.push(`  canIUse: () => true,`);
  L.push(`  nextTick: (fn) => Promise.resolve().then(fn),`);
  L.push(`  request: (o) => console.error("[wx.request stub]", o.method || "GET", o.url),`);
  L.push(`  onAppShow(){}, onAppHide(){}, onError(){}, onNetworkStatusChange(){}, onMemoryWarning(){},`);
  L.push(`  env: { USER_DATA_PATH: "/tmp" },`);
  L.push(`};`);
  L.push(``);
  L.push(`globalThis.App = (opts) => { _appInst = { ...opts, globalData: opts.globalData || {} }; try { opts.onLaunch?.call(_appInst, {}); } catch {} };`);
  L.push(`globalThis.getApp = () => _appInst;`);
  L.push(`globalThis.Page = () => {};`);
  L.push(`globalThis.Component = () => {};`);
  L.push(`globalThis.Behavior = (x) => x;`);
  L.push(`globalThis.definePlugin = () => {};`);
  L.push(`globalThis.requirePlugin = () => ({});`);
  L.push(`globalThis.getCurrentPages = () => [];`);
  L.push(`globalThis.__wxConfig = { appLaunchInfo: {}, accountInfo: { appId: ${JSON.stringify(opts.appid)} }, envVersion: "release", platform: "mac" };`);
  L.push(``);

  // ── Extracted modules ──
  L.push(`// ── Extracted modules (${usedKeys.length}) ──`);
  let wpChunkIncluded = false;
  for (const key of usedKeys) {
    const factory = ctx.modules[key];
    if (!factory) continue;
    let src;
    try { src = factory.toString(); } catch { continue; }
    // detect webpack chunk (single large define containing __webpack_require__)
    if (src.includes("__webpack_require__") && !wpChunkIncluded) {
      L.push(`// [webpack chunk — includes bundled sub-modules]`);
      wpChunkIncluded = true;
    }
    L.push(`_m[${JSON.stringify(key)}] = ${src};`);
    L.push(``);
  }

  // ── Entry + export ──
  L.push(`// ── Entry ──`);
  L.push(`const _entry = _req("", ${JSON.stringify(opts.entry)});`);
  L.push(``);

  if (opts.fn) {
    L.push(`export function ${opts.fn}(params) {`);
    L.push(`  if (typeof _entry.${opts.fn} === "function") return _entry.${opts.fn}(params);`);
    L.push(`  if (typeof _entry.default?.${opts.fn} === "function") return _entry.default.${opts.fn}(params);`);
    L.push(`  throw new Error("${opts.fn} not found on entry module");`);
    L.push(`}`);
  } else {
    L.push(`export default _entry;`);
  }
  L.push(``);

  // ── CLI ──
  L.push(`// ── CLI ──`);
  L.push(`const _cliArg = process.argv[2];`);
  L.push(`if (_cliArg) {`);
  if (opts.fn) {
    L.push(`  try {`);
    L.push(`    const params = JSON.parse(_cliArg);`);
    L.push(`    const result = ${opts.fn}(params);`);
    L.push(`    console.log(typeof result === "string" ? result : JSON.stringify(result));`);
    L.push(`  } catch (e) { console.error("Error:", e.message); process.exit(1); }`);
  } else {
    L.push(`  console.log(JSON.stringify(_entry));`);
  }
  L.push(`}`);

  return L.join("\n");
}

async function main() {
  const opts = parseArgs();
  if (!opts.appid || !opts.entry) {
    console.error("Usage: node scripts/sandbox-export.mjs <appid> --entry <module_path> [--fn name] [--verify code] [--output file]");
    process.exit(1);
  }

  const bundlePath = opts.bundlePath || findBundle(opts.appid);
  if (!bundlePath || !existsSync(bundlePath)) {
    console.error(`❌ app-service.js not found for ${opts.appid}. Run mp_analyze first.`);
    process.exit(1);
  }

  console.error(`Loading bundle: ${bundlePath}`);
  const ctx = loadBundle({ appid: opts.appid, bundlePath, storage: opts.storage, timeout: 30000 });
  console.error(`Loaded ${Object.keys(ctx.modules).length} modules`);

  // ── Verify (optional) ──
  let verifyResult = undefined;
  if (opts.verify) {
    console.error(`Verifying: ${opts.verify}`);
    try {
      const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
      const fn = new AsyncFunction("ctx", "requireMod", "wpRequire", "sandbox", `return (${opts.verify})`);
      verifyResult = await fn(ctx, ctx.requireMod, ctx.wpRequire, ctx.sandbox);
      console.error(`✅ Verify result: ${JSON.stringify(verifyResult)}`);
    } catch (e) {
      console.error(`❌ Verify failed: ${e.message}`);
      process.exit(1);
    }
  } else {
    // just require entry to populate cache
    try { ctx.requireMod(opts.entry); } catch (e) {
      console.error(`❌ Cannot require ${opts.entry}: ${e.message}`);
      process.exit(1);
    }
  }

  // ── Trace used modules ──
  const usedKeys = Object.keys(ctx.cache);
  console.error(`Traced ${usedKeys.length} modules in dependency graph`);

  // ── Generate standalone ──
  const code = generateStandalone(ctx, usedKeys, opts);

  const outPath = opts.output || join(PROJECT_ROOT, "static", "out", opts.appid, "signer.mjs");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, code);

  const sizeKB = (Buffer.byteLength(code) / 1024).toFixed(1);
  console.error(`\n📦 Exported: ${outPath} (${sizeKB} KB, ${usedKeys.length} modules)`);

  // summary to stdout (for MCP)
  const summary = {
    appid: opts.appid,
    entry: opts.entry,
    exportFn: opts.fn || "default",
    modules: usedKeys.length,
    outputPath: outPath,
    sizeKB: +sizeKB,
    verifyResult: verifyResult !== undefined ? verifyResult : null,
  };
  console.log(JSON.stringify(summary, null, 2));
}

main();
