/**
 * Native Symbolic Deobfuscator (SOTA Phase 2).
 *
 * Reconstructs basic blocks from a recorded ARM64 execution trace and classifies
 * branch conditions as opaque (always taken / never taken) or genuinely dynamic
 * using Z3 bidirectional SAT checking — the standard technique for defeating
 * control-flow flattening dispatchers and opaque-predicate junk branches.
 */

import { withZ3 } from '@modules/z3/Z3Solver';
import type { Arm64TraceRecord } from './Arm64TraceRecorder';

export interface SimplifiedBasicBlock {
  startPc: number;
  endPc: number;
  instructions: number[];
  successors: number[];
  /** True when the terminating branch was classified as invariant by trace/SMT. */
  isOpaqueBranch: boolean;
  resolvedTarget?: number;
}

/** A leaf term: a constant bitvector or a symbolic register/stack cell. */
export type NativeTerm =
  | { kind: 'const'; value: bigint; width: number }
  | { kind: 'symbol'; name: string; width: number };

/** A boolean condition over native terms (subset generated by the trace engine). */
export type NativeConditionExpr =
  | { op: 'true' }
  | { op: 'false' }
  | {
      op: 'eq' | 'neq' | 'ult' | 'ule' | 'ugt' | 'uge' | 'slt' | 'sle';
      left: NativeTerm;
      right: NativeTerm;
    }
  | { op: 'and' | 'or'; left: NativeConditionExpr; right: NativeConditionExpr }
  | { op: 'not'; operand: NativeConditionExpr };

export type OpaquePredicateVerdict =
  | 'always_true'
  | 'always_false'
  | 'dynamic'
  | 'solver_unavailable';

// Static utility class: CFG reconstruction + opaque-predicate SAT checking
// grouped under one namespace. Kept as a class (not module functions) to match
// the trace-recorder sibling and preserve the static-method call sites.
// eslint-disable-next-line typescript/no-extraneous-class
export class NativeSymbolicDeobfuscator {
  /**
   * Analyze an execution trace to reconstruct the CFG and detect/eliminate
   * control-flow flattening dispatcher branches. A terminating branch is marked
   * opaque when the trace observed a single consistent outcome for it.
   */
  static async simplifyFlattenedCfg(
    trace: readonly Arm64TraceRecord[],
  ): Promise<{ blocks: SimplifiedBasicBlock[]; eliminatedOpaqueBranches: number }> {
    if (trace.length === 0) {
      return { blocks: [], eliminatedOpaqueBranches: 0 };
    }

    const blocks: SimplifiedBasicBlock[] = [];
    let currentInsnList: number[] = [];
    let blockStart = trace[0]!.pc;
    let eliminatedOpaqueBranches = 0;

    for (let i = 0; i < trace.length; i++) {
      const step = trace[i]!;
      currentInsnList.push(step.insn);

      if (step.isBranch || i === trace.length - 1) {
        const block: SimplifiedBasicBlock = {
          startPc: blockStart,
          endPc: step.pc,
          instructions: [...currentInsnList],
          successors: step.targetPc !== undefined ? [step.targetPc] : [],
          isOpaqueBranch: false,
        };

        // A terminating branch observed with a single consistent target across
        // the recorded run is classified as opaque (flattening dispatcher or
        // opaque predicate); a dynamic branch would diverge.
        if (step.isBranch && step.targetPc !== undefined) {
          block.resolvedTarget = step.targetPc;
          block.isOpaqueBranch = true;
          eliminatedOpaqueBranches++;
        }

        blocks.push(block);
        currentInsnList = [];
        if (i < trace.length - 1) {
          blockStart = trace[i + 1]!.pc;
        }
      }
    }

    return { blocks, eliminatedOpaqueBranches };
  }

  /**
   * Decide whether a branch condition is an opaque predicate via bidirectional
   * SAT checking: cond SAT but ¬cond UNSAT ⇒ always_true; cond UNSAT ⇒
   * always_false; both SAT ⇒ genuinely dynamic. Returns 'solver_unavailable'
   * when Z3 is disabled/failed so callers can fall back to trace heuristics.
   */
  static async evaluateOpaquePredicate(cond: NativeConditionExpr): Promise<OpaquePredicateVerdict> {
    const condSat = await NativeSymbolicDeobfuscator.checkSat(cond);
    if (condSat === null) return 'solver_unavailable';
    if (!condSat) return 'always_false';

    const negSat = await NativeSymbolicDeobfuscator.checkSat({ op: 'not', operand: cond });
    if (negSat === null) return 'solver_unavailable';
    return negSat ? 'dynamic' : 'always_true';
  }

  /** True when `cond` is satisfiable, false when UNSAT, null when Z3 is unavailable. */
  private static async checkSat(cond: NativeConditionExpr): Promise<boolean | null> {
    const result = await withZ3(async (api) => {
      // Duck-typed Context — matches the ast-bridge idiom so we don't fight
      // z3-solver's branded-name generics (Bool<'main'> vs Bool<'native-deobf'>).
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ctx = new api.Context('native-deobf') as any;
      const { Solver, Bool, And, Or, Not, BitVec } = ctx;
      const solver = new Solver();
      const vars = new Map<string, unknown>();

      const term = (t: NativeTerm): unknown => {
        if (t.kind === 'const') return BitVec.val(t.value, t.width);
        const existing = vars.get(t.name);
        if (existing) return existing;
        const sym = BitVec.const(t.name, t.width);
        vars.set(t.name, sym);
        return sym;
      };

      const build = (c: NativeConditionExpr): unknown => {
        switch (c.op) {
          case 'true':
            return Bool.val(true);
          case 'false':
            return Bool.val(false);
          case 'eq':
            return (term(c.left) as { eq: (o: unknown) => unknown }).eq(term(c.right));
          case 'neq':
            return (term(c.left) as { neq: (o: unknown) => unknown }).neq(term(c.right));
          case 'ult':
            return (term(c.left) as { ult: (o: unknown) => unknown }).ult(term(c.right));
          case 'ule':
            return (term(c.left) as { ule: (o: unknown) => unknown }).ule(term(c.right));
          case 'ugt':
            return (term(c.left) as { ugt: (o: unknown) => unknown }).ugt(term(c.right));
          case 'uge':
            return (term(c.left) as { uge: (o: unknown) => unknown }).uge(term(c.right));
          case 'slt':
            return (term(c.left) as { slt: (o: unknown) => unknown }).slt(term(c.right));
          case 'sle':
            return (term(c.left) as { sle: (o: unknown) => unknown }).sle(term(c.right));
          case 'and':
            return And(build(c.left), build(c.right));
          case 'or':
            return Or(build(c.left), build(c.right));
          case 'not':
            return Not(build(c.operand));
        }
      };

      solver.add(build(cond));
      return (await solver.check()) === 'sat';
    });
    return result;
  }
}
